#!/usr/bin/python3
# vi:se ts=4 sts=4 et:
import socket
#import socketserver
import http.server
import sys

class Simple6HTTPRequestHandler(http.server.SimpleHTTPRequestHandler):
   address_family = socket.AF_INET6

def run(HandlerClass = Simple6HTTPRequestHandler,
         ServerClass = http.server.HTTPServer, protocol="HTTP/1.0"):
    """Test the HTTP request handler class.

    This runs an HTTP server on port 8080 (or the first command line
    argument).

    """

    if sys.argv[1:]:
        port = int(sys.argv[1])
    else:
        port = 8080
    server_address = ('', port)

    HandlerClass.protocol_version = protocol
    httpd = ServerClass(server_address, HandlerClass)

    sa = httpd.socket.getsockname()
    print("Serving HTTP on", sa[0], "port", sa[1], "...")
    try:
        httpd.serve_forever()
    except KeyboardInterrupt:
        print("\nKeyboard interrupt received, exiting.")
        httpd.server_close()
        sys.exit(0)

if __name__ == '__main__':
    run(HandlerClass=Simple6HTTPRequestHandler)
