set nocompatible
set nopaste
set pastetoggle=<f2>
set syntax=ON
" Use secure modeline plug-in
set nomodeline
if $USER == "root"
 set noswapfile
else
 set swapfile
endif
" filler to avoid the line above being recognized as a modeline
" filler
" filler
