.\"                                      Hey, EMACS: -*- nroff -*-
.\" (C) Copyright 2013 Osamu Aoki <osamu@debian.org>,
.\"
.TH FRIDGE SECTION "April  6, 2013"
.SH NAME
jane, joe, tom \- program to tell one's beer supply
.SH SYNOPSIS
.B jane
.br
.B joe
.br
.B tom
.SH DESCRIPTION
This manual page documents briefly the
.B jane ,
.B joe
and
.B tom
commands.
.PP
.SH OPTIONS
None.
.SH SEE ALSO
The programs are documented fully in my brain.
