all:
	$(MAKE) -C path $@
	$(MAKE) -C scope $@
	$(MAKE) -C package1 $@
	$(MAKE) -C package2 $@
	$(MAKE) -C package3 $@

%:
	$(MAKE) -C path $@
	$(MAKE) -C scope $@
	$(MAKE) -C package1 $@
	$(MAKE) -C package2 $@
	$(MAKE) -C package3 $@
