baseurl = "/"
languageCode = "en-us"
title = "Goofing Osamu"
# active theme (default submodule)
theme = "hugo-xmin"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"
# allow all tags automatically
#tags = ["debian", "blog", "personal", "clean", "simple", "starter", "minimalist"]

[permalinks]
    en = "/en/:year/:month/:day/:slug/"
    jp = "/jp/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
[[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 3
[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 4
[[menu.main]]
    name = "English"
    url = "/en/"
    weight = 5
[[menu.main]]
    name = "Japanese"
    url = "/jp/"
    weight = 6
[[menu.main]]
    name = "Subscribe"
    url = "/index.xml"

[params]
    description = "Random memos of Goofing Osamu"
    footer = "&copy; 2019 [Osamu Aoki](https://github.com/osamuaoki)"
