all:
	$(MAKE) -C c $@
	$(MAKE) -C cxx $@
	$(MAKE) -C sh $@
	$(MAKE) -C lua $@
	$(MAKE) -C python $@
	$(MAKE) -C perl $@
	$(MAKE) -C vala $@
	$(MAKE) -C bench $@

%:
	$(MAKE) -C c $@
	$(MAKE) -C cxx $@
	$(MAKE) -C sh $@
	$(MAKE) -C lua $@
	$(MAKE) -C python $@
	$(MAKE) -C perl $@
	$(MAKE) -C vala $@
	$(MAKE) -C bench $@

