all:
	$(MAKE) -C cp-block $@
	$(MAKE) -C cp-blockbig $@
	$(MAKE) -C cp-char $@
	$(MAKE) -C cp-mmap-memcpy $@
	$(MAKE) -C cp-mmap-write $@
	$(MAKE) -C size-block $@
	$(MAKE) -C size-char $@
	$(MAKE) -C size-lseek $@
	$(MAKE) -C size-stat $@
	$(MAKE) -C bench $@

%:
	$(MAKE) -C cp-block $@
	$(MAKE) -C cp-blockbig $@
	$(MAKE) -C cp-char $@
	$(MAKE) -C cp-mmap-memcpy $@
	$(MAKE) -C cp-mmap-write $@
	$(MAKE) -C size-block $@
	$(MAKE) -C size-char $@
	$(MAKE) -C size-lseek $@
	$(MAKE) -C size-stat $@
	$(MAKE) -C bench $@
