/* gui-1.c generated by valac 0.20.1, the Vala compiler
 * generated from gui-1.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>

#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))


extern gint i;
gint i = 0;

void on_button1_clicked (GtkButton* button);
void on_window1_destroy (GtkWindow* window);
gint _vala_main (gchar** args, int args_length1);


void on_button1_clicked (GtkButton* button) {
	gint _tmp0_;
	GtkButton* _tmp1_;
	gint _tmp2_;
	gchar* _tmp3_ = NULL;
	gchar* _tmp4_;
	g_return_if_fail (button != NULL);
	_tmp0_ = i;
	i = _tmp0_ + 1;
	_tmp1_ = button;
	_tmp2_ = i;
	_tmp3_ = g_strdup_printf ("Hello, World!\nClick count = %i", _tmp2_);
	_tmp4_ = _tmp3_;
	gtk_button_set_label (_tmp1_, _tmp4_);
	_g_free0 (_tmp4_);
}


void on_window1_destroy (GtkWindow* window) {
	g_return_if_fail (window != NULL);
	gtk_main_quit ();
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


gint _vala_main (gchar** args, int args_length1) {
	gint result = 0;
	GError * _inner_error_ = NULL;
	gtk_init (&args_length1, &args);
	i = 0;
	{
		GtkBuilder* _tmp0_;
		GtkBuilder* builder;
		GtkBuilder* _tmp1_;
		GtkBuilder* _tmp2_;
		GtkBuilder* _tmp3_;
		GObject* _tmp4_ = NULL;
		GtkWindow* _tmp5_;
		GtkWindow* window;
		GtkWindow* _tmp6_;
		_tmp0_ = gtk_builder_new ();
		builder = _tmp0_;
		_tmp1_ = builder;
		gtk_builder_add_from_file (_tmp1_, "clickme.glade", &_inner_error_);
		if (_inner_error_ != NULL) {
			_g_object_unref0 (builder);
			goto __catch0_g_error;
		}
		_tmp2_ = builder;
		gtk_builder_connect_signals (_tmp2_, NULL);
		_tmp3_ = builder;
		_tmp4_ = gtk_builder_get_object (_tmp3_, "window1");
		_tmp5_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp4_, GTK_TYPE_WINDOW) ? ((GtkWindow*) _tmp4_) : NULL);
		window = _tmp5_;
		_tmp6_ = window;
		gtk_widget_show_all ((GtkWidget*) _tmp6_);
		_g_object_unref0 (window);
		_g_object_unref0 (builder);
	}
	goto __finally0;
	__catch0_g_error:
	{
		GError* e = NULL;
		FILE* _tmp7_;
		GError* _tmp8_;
		const gchar* _tmp9_;
		e = _inner_error_;
		_inner_error_ = NULL;
		_tmp7_ = stderr;
		_tmp8_ = e;
		_tmp9_ = _tmp8_->message;
		fprintf (_tmp7_, "Could not load UI: %s\n", _tmp9_);
		result = 1;
		_g_error_free0 (e);
		return result;
	}
	__finally0:
	if (_inner_error_ != NULL) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return 0;
	}
	gtk_main ();
	result = 0;
	return result;
}


int main (int argc, char ** argv) {
	g_type_init ();
	return _vala_main (argv, argc);
}



