all:
	$(MAKE) -C gtk3 $@
	$(MAKE) -C gtk3-glade $@
	$(MAKE) -C vala $@
	$(MAKE) -C vala-glade $@
	$(MAKE) -C python-path $@

%:
	$(MAKE) -C gtk3 $@
	$(MAKE) -C gtk3-glade $@
	$(MAKE) -C vala $@
	$(MAKE) -C vala-glade $@
	$(MAKE) -C python-path $@

