/* prime.c generated by valac 0.16.1, the Vala compiler
 * generated from prime.vala, and touched up :-) */

/* The same result as Vala code for slowness */

#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>


int main (int argc, char ** argv) {
	/* g_type_init (); */
	glong n_max = atol (argv[1]);
	GList* p = NULL;
	glong n;
	n = (glong) 1;
	while (TRUE) {
		n = n + 1;
		gboolean flag_prime;
		flag_prime = FALSE;
		if (!(n < n_max)) {
			break;
		}
		flag_prime = TRUE;
		GList* i_it = NULL;
		for (i_it = p; i_it != NULL; i_it = i_it->next) {
			glong i = GPOINTER_TO_INT (i_it->data);
			glong n_div_i;
			glong n_mod_i;
			n_div_i = n / i;
			n_mod_i = n - (n_div_i * i);
			if (n_mod_i == ((glong) 0)) {
				flag_prime = FALSE;
				break;
			}
			if (n_div_i < i) {
				break;
			}
		}
		if (flag_prime == TRUE) {
			p = g_list_append (p, GINT_TO_POINTER (n));
		}
	}
	GList* i_it = NULL;
	for (i_it = p; i_it != NULL; i_it = i_it->next) {
		glong i = 0L;
		i = GPOINTER_TO_INT (i_it->data);
		{
			fprintf (stdout, "%ld\n", i);
		}
	}
        if (p != NULL) {
            p = (g_list_free (p), NULL);
        }
	return EXIT_SUCCESS;
}

