#!/usr/bin/python
def main():
    """Print the Fibonacci series up to n."""
    import argparse, sys
    parser = argparse.ArgumentParser(description='Print the Fibonacci series up to n.')
    parser.add_argument('args', nargs=1, help='arguments')
    args = parser.parse_args()
    n = int(args.args[0])
    fib(n)

def fib(n):
    """Print the Fibonacci series up to n."""
    a, b = 0, 1
    while b < n:
        print b,
        a, b = b, a + b

if __name__ == '__main__': 
    main()
