all:
	$(MAKE) -C c-array $@
	$(MAKE) -C c-list $@
	$(MAKE) -C c-pthread $@
	$(MAKE) -C c-pthread2 $@
	$(MAKE) -C sh $@
	$(MAKE) -C lua $@
	$(MAKE) -C python $@
	$(MAKE) -C perl $@
	$(MAKE) -C vala $@
	$(MAKE) -C vala-gee $@
	$(MAKE) -C bench $@

%:
	$(MAKE) -C c-array $@
	$(MAKE) -C c-list $@
	$(MAKE) -C c-pthread $@
	$(MAKE) -C c-pthread2 $@
	$(MAKE) -C sh $@
	$(MAKE) -C lua $@
	$(MAKE) -C python $@
	$(MAKE) -C perl $@
	$(MAKE) -C vala $@
	$(MAKE) -C vala-gee $@
	$(MAKE) -C bench $@
