#!/usr/bin/perl -w
use constant false => 0;
use constant true  => 1;
$n_max = "$ARGV[0]" + 0;
@p = (); # list containing all primes found
for ($n = 2; $n < $n_max; $n++) {
    $flag_prime = true;
    # search for all pimes found
    foreach $i (@p) {
        $n_div_i = int($n / $i);
        $n_mod_i = $n % $i;
        if ($n_mod_i == 0) {
            # found to be non-prime
            $flag_prime = false;
            last; # found not to be prime
        }
        if ($n_div_i < $i) {
            last; # no use doing more i-loop if n < i*i
        }
    }
    if ($flag_prime == true) {
        push (@p, $n);
    }
}
foreach $i (@p) {
    print "$i\n";
}

