/* cli-3.c generated by valac 0.20.1, the Vala compiler
 * generated from cli-3.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include <locale.h>


#define TYPE_CLI (cli_get_type ())
#define CLI(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_CLI, Cli))
#define CLI_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_CLI, CliClass))
#define IS_CLI(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_CLI))
#define IS_CLI_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_CLI))
#define CLI_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_CLI, CliClass))

typedef struct _Cli Cli;
typedef struct _CliClass CliClass;
typedef struct _CliPrivate CliPrivate;
#define _g_option_context_free0(var) ((var == NULL) ? NULL : (var = (g_option_context_free (var), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

struct _Cli {
	GObject parent_instance;
	CliPrivate * priv;
};

struct _CliClass {
	GObjectClass parent_class;
};


static gpointer cli_parent_class = NULL;
static gboolean cli_append;
static gboolean cli_append = FALSE;
static gboolean cli_verbose;
static gboolean cli_verbose = FALSE;
static gboolean cli_op_long;
static gboolean cli_op_long = FALSE;
static gchar* cli_filename;
static gchar* cli_filename = NULL;
static gchar* cli_longextra;
static gchar* cli_longextra = NULL;
static gchar** cli_sources;
static gchar** cli_sources = NULL;

GType cli_get_type (void) G_GNUC_CONST;
enum  {
	CLI_DUMMY_PROPERTY
};
static gint cli_parse (Cli* self, gchar** args, int args_length1);
static gint cli_run (Cli* self);
gint cli_main (gchar** args, int args_length1);
Cli* cli_new (void);
Cli* cli_construct (GType object_type);
static void cli_finalize (GObject* obj);
static gint _vala_array_length (gpointer array);

static const GOptionEntry CLI_options[7] = {{"append", 'a', 0, G_OPTION_ARG_NONE, &cli_append, "Set append mode", NULL}, {"verbose", 'v', 0, G_OPTION_ARG_NONE, &cli_verbose, "Set verbose mode", NULL}, {"file", 'f', 0, G_OPTION_ARG_FILENAME, &cli_filename, "Use F file", "F"}, {"long", (gchar) 0, 0, G_OPTION_ARG_NONE, &cli_op_long, "Set long mode", NULL}, {"longextra", (gchar) 0, 0, G_OPTION_ARG_STRING, &cli_longextra, "Set longextra to M", "M"}, {"", (gchar) 0, 0, G_OPTION_ARG_FILENAME_ARRAY, &cli_sources, NULL, "FILE..."}, {NULL}};

static gint cli_parse (Cli* self, gchar** args, int args_length1) {
	gint result = 0;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (self != NULL, 0);
	{
		GOptionContext* _tmp0_;
		GOptionContext* opt_context;
		GOptionContext* _tmp1_;
		GOptionContext* _tmp2_;
		GOptionContext* _tmp3_;
		_tmp0_ = g_option_context_new ("- Cli");
		opt_context = _tmp0_;
		_tmp1_ = opt_context;
		g_option_context_set_help_enabled (_tmp1_, TRUE);
		_tmp2_ = opt_context;
		g_option_context_add_main_entries (_tmp2_, CLI_options, NULL);
		_tmp3_ = opt_context;
		g_option_context_parse (_tmp3_, &args_length1, &args, &_inner_error_);
		if (_inner_error_ != NULL) {
			_g_option_context_free0 (opt_context);
			if (_inner_error_->domain == G_OPTION_ERROR) {
				goto __catch0_g_option_error;
			}
			_g_option_context_free0 (opt_context);
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return 0;
		}
		_g_option_context_free0 (opt_context);
	}
	goto __finally0;
	__catch0_g_option_error:
	{
		GError* e = NULL;
		FILE* _tmp4_;
		GError* _tmp5_;
		const gchar* _tmp6_;
		FILE* _tmp7_;
		gchar** _tmp8_;
		gint _tmp8__length1;
		const gchar* _tmp9_;
		e = _inner_error_;
		_inner_error_ = NULL;
		_tmp4_ = stdout;
		_tmp5_ = e;
		_tmp6_ = _tmp5_->message;
		fprintf (_tmp4_, "%s\n", _tmp6_);
		_tmp7_ = stdout;
		_tmp8_ = args;
		_tmp8__length1 = args_length1;
		_tmp9_ = _tmp8_[0];
		fprintf (_tmp7_, "Run '%s --help' to see a full list of available command line options.\n", _tmp9_);
		result = 1;
		_g_error_free0 (e);
		return result;
	}
	__finally0:
	if (_inner_error_ != NULL) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return 0;
	}
	result = 0;
	return result;
}


static gint cli_run (Cli* self) {
	gint result = 0;
	gboolean _tmp0_;
	gboolean _tmp2_;
	gboolean _tmp4_;
	const gchar* _tmp6_;
	const gchar* _tmp9_;
	gchar** _tmp12_;
	gint _tmp12__length1;
	g_return_val_if_fail (self != NULL, 0);
	_tmp0_ = cli_verbose;
	if (_tmp0_) {
		FILE* _tmp1_;
		_tmp1_ = stdout;
		fprintf (_tmp1_, "Cli: verbose ON\n");
	}
	_tmp2_ = cli_append;
	if (_tmp2_) {
		FILE* _tmp3_;
		_tmp3_ = stdout;
		fprintf (_tmp3_, "Cli: appemd ON\n");
	}
	_tmp4_ = cli_op_long;
	if (_tmp4_) {
		FILE* _tmp5_;
		_tmp5_ = stdout;
		fprintf (_tmp5_, "Cli: long ON\n");
	}
	_tmp6_ = cli_filename;
	if (_tmp6_ != NULL) {
		FILE* _tmp7_;
		const gchar* _tmp8_;
		_tmp7_ = stdout;
		_tmp8_ = cli_filename;
		fprintf (_tmp7_, "Cli: file = %s\n", _tmp8_);
	}
	_tmp9_ = cli_longextra;
	if (_tmp9_ != NULL) {
		FILE* _tmp10_;
		const gchar* _tmp11_;
		_tmp10_ = stdout;
		_tmp11_ = cli_longextra;
		fprintf (_tmp10_, "Cli: longextra = %s\n", _tmp11_);
	}
	_tmp12_ = cli_sources;
	_tmp12__length1 = _vala_array_length (cli_sources);
	if (_tmp12_ != NULL) {
		gint i;
		gchar** _tmp13_;
		gint _tmp13__length1;
		i = 0;
		_tmp13_ = cli_sources;
		_tmp13__length1 = _vala_array_length (cli_sources);
		{
			gchar** s_collection = NULL;
			gint s_collection_length1 = 0;
			gint _s_collection_size_ = 0;
			gint s_it = 0;
			s_collection = _tmp13_;
			s_collection_length1 = _tmp13__length1;
			for (s_it = 0; s_it < _tmp13__length1; s_it = s_it + 1) {
				gchar* _tmp14_;
				gchar* s = NULL;
				_tmp14_ = g_strdup (s_collection[s_it]);
				s = _tmp14_;
				{
					FILE* _tmp15_;
					gint _tmp16_;
					const gchar* _tmp17_;
					gint _tmp18_;
					_tmp15_ = stdout;
					_tmp16_ = i;
					_tmp17_ = s;
					fprintf (_tmp15_, "sources[%i]=%s\n", _tmp16_, _tmp17_);
					_tmp18_ = i;
					i = _tmp18_ + 1;
					_g_free0 (s);
				}
			}
		}
	}
	result = 0;
	return result;
}


gint cli_main (gchar** args, int args_length1) {
	gint result = 0;
	FILE* _tmp0_;
	gchar** _tmp1_;
	gint _tmp1__length1;
	const gchar* _tmp2_;
	FILE* _tmp3_;
	gchar** _tmp4_;
	gint _tmp4__length1;
	const gchar* _tmp5_;
	gchar* _tmp6_ = NULL;
	gchar* _tmp7_;
	Cli* _tmp8_;
	Cli* cli;
	gchar** _tmp9_;
	gint _tmp9__length1;
	gint _tmp10_ = 0;
	setlocale (LC_ALL, "");
	_tmp0_ = stdout;
	_tmp1_ = args;
	_tmp1__length1 = args_length1;
	_tmp2_ = _tmp1_[0];
	fprintf (_tmp0_, "command  = %s\n", _tmp2_);
	_tmp3_ = stdout;
	_tmp4_ = args;
	_tmp4__length1 = args_length1;
	_tmp5_ = _tmp4_[0];
	_tmp6_ = g_path_get_basename (_tmp5_);
	_tmp7_ = _tmp6_;
	fprintf (_tmp3_, "basename = %s\n", _tmp7_);
	_g_free0 (_tmp7_);
	_tmp8_ = cli_new ();
	cli = _tmp8_;
	_tmp9_ = args;
	_tmp9__length1 = args_length1;
	cli_parse (cli, _tmp9_, _tmp9__length1);
	_tmp10_ = cli_run (cli);
	result = _tmp10_;
	_g_object_unref0 (cli);
	return result;
}


int main (int argc, char ** argv) {
	g_type_init ();
	return cli_main (argv, argc);
}


Cli* cli_construct (GType object_type) {
	Cli * self = NULL;
	self = (Cli*) g_object_new (object_type, NULL);
	return self;
}


Cli* cli_new (void) {
	return cli_construct (TYPE_CLI);
}


static void cli_class_init (CliClass * klass) {
	cli_parent_class = g_type_class_peek_parent (klass);
	G_OBJECT_CLASS (klass)->finalize = cli_finalize;
}


static void cli_instance_init (Cli * self) {
}


static void cli_finalize (GObject* obj) {
	Cli * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_CLI, Cli);
	G_OBJECT_CLASS (cli_parent_class)->finalize (obj);
}


GType cli_get_type (void) {
	static volatile gsize cli_type_id__volatile = 0;
	if (g_once_init_enter (&cli_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (CliClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) cli_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (Cli), 0, (GInstanceInitFunc) cli_instance_init, NULL };
		GType cli_type_id;
		cli_type_id = g_type_register_static (G_TYPE_OBJECT, "Cli", &g_define_type_info, 0);
		g_once_init_leave (&cli_type_id__volatile, cli_type_id);
	}
	return cli_type_id__volatile;
}


static gint _vala_array_length (gpointer array) {
	int length;
	length = 0;
	if (array) {
		while (((gpointer*) array)[length]) {
			length++;
		}
	}
	return length;
}



