#!/bin/sh
cat - <<EOF | gpg -d --no-mdc-warning | while read x ;do eval "$x"; done
-----BEGIN PGP MESSAGE-----
Version: GnuPG v1.4.12 (GNU/Linux)

jA0EAwMCzD3qgP+sk8RgyU+RoomNr++CuLZb0IC4xELogppqajA2V6IrGAg8Vh5w
IEhoJXm8FqA6QuaT7+sqnf5GzvYy8JkiSr4Ucd1cL0xCF6F+yLmbjFh/L5k68LLa
=Kx5I
-----END PGP MESSAGE-----
EOF
