all:
	$(MAKE) -C c $@
	$(MAKE) -C sh $@
	$(MAKE) -C lua $@
	#$(MAKE) -C python $@
	$(MAKE) -C perl $@
	$(MAKE) -C vala $@

%:
	$(MAKE) -C c $@
	$(MAKE) -C sh $@
	$(MAKE) -C lua $@
	#$(MAKE) -C python $@
	$(MAKE) -C perl $@
	$(MAKE) -C vala $@
